version: "3.9"
services:
  currency_exchanger_backend:
    build:
      context: ./apps/backend
    container_name: "currency_exchanger.backend"
    ports:
      - "3000:3000"
  currency_exchanger_frontend:
    build:
      context: ./apps/frontend
    container_name: "currency_exchanger.frontend"
    ports:
      - "3001:80"
    depends_on:
      - currency_exchanger_backend